name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  push:
  workflow_dispatch:

jobs:
  build-node:
    runs-on: self-hosted
    steps:
      - name: checkout sonarqube
        uses: actions/checkout@v4

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: user/app:latest

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      
