name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  push:
  workflow_dispatch:

jobs:
  build-node:
    runs-on: self-hosted
    steps:
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: user/app:latest
